# Use OpenJDK 11 from AdoptOpenJDK
# https://hub.docker.com/r/adoptopenjdk/openjdk11
image: adoptopenjdk/openjdk11:alpine

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

java:
  stage: build
  before_script:
    # Install and log maven version
    - apk add maven
    - mvn -version
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
      - "target/*.jar"
